version: "3"
services:
  db01:
    image: "postgres:11"
    container_name: "etl_postgres_01"
    ports:
      - "54320:5432"
    volumes:
      - etl_dbdata_01:/var/lib/postgresql/data
      - ./tables:/root/tables
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
  db02:
    image: "postgres:11"
    container_name: "etl_postgres_02"
    ports:
      - "5433:5432"
    volumes:
      - etl_dbdata_02:/var/lib/postgresql/data
      - ./tables:/root/tables
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
  airflow:
    image: puckel/docker-airflow
    container_name: "airflow"
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/usr/local/airflow/operators/
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./operators:/usr/local/airflow/operators/
    command: webserver
volumes:
  etl_dbdata_01:
  etl_dbdata_02: